# Generated by Django 4.1.5 on 2023-01-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main'], 'verbose_name': 'Тематика Статьи', 'verbose_name_plural': 'Тематики Статьи'},
        ),
    ]
